THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
HUB_COMPOSE ?= deploy/imwald/compose.hub.yaml
DB_DIR := $(THIS_DIR)deploy/unfold-db
include $(THIS_DIR)deploy/hub-app.mk

.DEFAULT_GOAL := help
